#pragma once

#define TRANSPOSITION_TABLE
#define PV_SEARCH
#define NULL_MOVE_PRUNING
//#define INTERNAL_ITERATIVE_DEEPENING

#define MAX_MOVES 100
#define MAX_DEPTH 20

#define DEFAULT_HASH_TABLE_SIZE 32